### ISSUE TITLE
Internal error: Failed to allocate counts or TMP when assigning g in gforce

### ISSUE THREAD

**Issue by maharshi14** [RegulatoryGenomicsGroup/chicdiff#5]
Hi! 

**My Chicdiff script is as follows:**

library("Chicdiff")

setwd("scratch/Chicdiff/")

designDir <- file.path("/home/s1786487/scratch/Chicdiff/DesignDir")

countData <- list(
  growing = c(Growing.Rep1 = file.path("/home/s1786487/scratch/Chicdiff/Growing.Rep1/chicagoTools.downsampled.chinput"),
              Growing.Rep2 = file.path("/home/s1786487/scratch/Chicdiff/Growing.Rep2/chicagoTools.downsampled.chinput")
  ),
  
  senesence = c(Senescent.Rep1 = file.path("/home/s1786487/scratch/Chicdiff/Senescent.Rep1/chicagoTools.downsampled.chinput"),
                Senescent.Rep2 = file.path("/home/s1786487/scratch/Chicdiff/Senescent.Rep2/chicagoTools.downsampled.chinput")
  )
)

chicagoData <- list(
  growing = c(Growing.Rep1 = file.path("/home/s1786487/scratch/Chicdiff/Growing.Rep1/Growing.Rep1.Rds"),
              Growing.Rep2 = file.path("/home/s1786487/scratch/Chicdiff/Growing.Rep2/Growing.Rep2.Rds")
  ),
  
  senesence = c(Senescent.Rep1 = file.path("/home/s1786487/scratch/Chicdiff/Senescent.Rep1/Sen.Rep1.Rds"),
                Senescent.Rep2 = file.path("/home/s1786487/scratch/Chicdiff/Senescent.Rep2/Sen.Rep2.Rds")
  )
)

peakFiles_growing <- "/home/s1786487/scratch/Chicdiff/PeakFiles/Growing_merged-matrix.txt"
peakFiles_senescent <- "/home/s1786487/scratch/Chicdiff/PeakFiles/Senescent_merged-matrix.txt"

chicdiff.settings <- setChicdiffExperiment(designDir = designDir,
                                           chicagoData = chicagoData,
                                           countData = countData,
                                           peakfiles = c(peakFiles_growing,peakFiles_senescent),  #not sure if listing multiple peak files in a vector is the problem here or not
                                           outprefix="Chicdiff_Growing-vs-Senescent",
                                           settings = list(parallel=F))

output <- chicdiffPipeline(chicdiff.settings)

**After the following standard outputs:**

*** Running getRegionUniverse

*** Running getControlRegionUniverse

*** Running getFullRegionData

Reading data for significant interactions

Reading Chicago dataset 1 of 4 : growing.Growing.Rep1
Collecting Bmean and Tmean
Recalculating distSign
Collecting bait parameters (s_j and tblb)
Collecting other end parameters (s_i and tlb)
Collecting Tmean
Imputing missing Tmeans
Reconstructing the distance function
Reconstructing Bmean

Reading Chicago dataset 2 of 4 : growing.Growing.Rep2
Collecting Bmean and Tmean
Recalculating distSign
Collecting bait parameters (s_j and tblb)
Collecting other end parameters (s_i and tlb)
Collecting Tmean
Imputing missing Tmeans
Reconstructing the distance function
Reconstructing Bmean

Reading Chicago dataset 3 of 4 : senesence.Senescent.Rep1
Collecting Bmean and Tmean
Recalculating distSign
Collecting bait parameters (s_j and tblb)
Collecting other end parameters (s_i and tlb)
Collecting Tmean
Imputing missing Tmeans
Reconstructing the distance function
Reconstructing Bmean

Reading Chicago dataset 4 of 4 : senesence.Senescent.Rep2
Collecting Bmean and Tmean
Recalculating distSign
Collecting bait parameters (s_j and tblb)
Collecting other end parameters (s_i and tlb)
Collecting Tmean
Imputing missing Tmeans
Reconstructing the distance function
Reconstructing Bmean

Saving counts

Reading count data for growing.Growing.Rep1
|--------------------------------------------------|
|==================================================|
Reading count data for growing.Growing.Rep2
|--------------------------------------------------|
|==================================================|
Reading count data for senesence.Senescent.Rep1
|--------------------------------------------------|
|==================================================|
Reading count data for senesence.Senescent.Rep2
|--------------------------------------------------|
|==================================================|

Collecting distances for CountOut
Processing count data

Reading data for control interactions

Reading Chicago dataset 1 of 4 : growing.Growing.Rep1
Collecting Bmean and Tmean
Recalculating distSign
Collecting bait parameters (s_j and tblb)
Collecting other end parameters (s_i and tlb)

I get the following error: 

Error in gforce(thisEnv, jsub, o__, f__, len__, irows) : 
  Internal error: Failed to allocate counts or TMP when assigning g in gforce

Can't seem to troubleshoot it so far, any ideas on the possible causes?

Thanks!

**Comment by mspivakov** [comment]
This looks like a data.table issue. Could it be that you've run out of memory?

**Comment by maharshi14** [comment]
Thank you so much for the error, indeed it was a memory issue. 

It ran perfectly until the IHWcorrection, where it fails to save the plots made for the unweighted p-values decision boundaries, with the error:

Error: 'ggsave' is not an exported object from 'namespace:cowplot'

I have tried using both ggplot2 and cowplot libraries attached and then not attached, but the error is still the same. 

Any help on this would be much appreciated, thanks!

**Comment by maharshi14** [comment]
Okay so I realised this was an issue already, I used **trace** to edit the IHWcorrection code, let's see if it works now!

Thanks!

**Comment by mspivakov** [comment]
Thanks for the heads up, we will have a look why this issue pops up again. Just to double check - are you using the latest versions of cowplot and ggplot2?

**Comment by mspivakov** [comment]
We couldn't reproduce this error, so can you please post your sessionInfo()?

**Comment by vmalysheva** [comment]
Hi,

You have got an older version of Chicdiff.
The current is 0.5 :)

**Comment by vmalysheva** [comment]
Thanks for proposing this correction. Sadly, it doesn't work like that, because for 
where="package:cowplot"
to work, you need cowplot already 'requested for use' before. However, at that point in Chicdiff, the cowplot was not called yet and thus where="package:cowplot" will not work. 

One way to mitigate this issue is to straightaway go for:
cowplot::ggsave2()
without the if else.

The version 0.5 is essentially doing that.

Also there are two other instances prior the place where you inserted the 'ifelse', where the cowplot::ggsave was used. For control ihw plots - we simply replaced it for ggsave (without cowplot), which is coming form ggplot2.

However for the plotDiffbaits we need the cowplot's ggsave2.
So, as I mentioned before you can just do cowplot::ggsave2() and this should work :)
